create database Decodelabs;
use Decodelabs;

show tables;

select * from dataset_project;
-- Which orders used the "FREESHIP" coupon code and had a TotalPrice over $1,000?
select * from dataset_project where CouponCode like "FREESHIP" and TotalPrice > 1000; 

-- List all orders with OrderStatus = 'Cancelled' that were paid for with a Credit Card.
select * from dataset_project where OrderStatus = "Cancelled" and PaymentMethod = "Credit Card";

-- ORDER BY
-- What are the 10 highest-value orders (by TotalPrice), and which product/customer do they belong to?
select CustomerID, Product, TotalPrice from dataset_project order by TotalPrice DESC limit 10;

-- List all "Laptop" orders sorted by Date from earliest to most recent.
select * from dataset_project where Product like "Laptop" order by date ASC;

-- How many orders fall into each OrderStatus category (Pending, Shipped, Delivered, Cancelled, Returned)?
select OrderStatus, count(*) from dataset_project group by OrderStatus order by count(OrderStatus) DESC;

-- How many orders came from each ReferralSource?
select ReferralSource, count(*) from dataset_project group by ReferralSource order by count(ReferralSource) DESC;

-- What is the total revenue (SUM of TotalPrice) generated by each Product?
select Product, sum(TotalPrice) AS TotalRevenue from dataset_project group by Product order by TotalRevenue DESC; 

-- What is the total revenue by PaymentMethod?
select PaymentMethod, sum(TotalPrice) AS TotalRevenue from dataset_project group by PaymentMethod order by TotalRevenue;

-- What is the average order value (TotalPrice) for each Product?
select Product, avg(TotalPrice) AS AveragePrice from dataset_project group by Product order by AveragePrice DESC;

-- What is the average Quantity ordered per ReferralSource?
select ReferralSource, avg(Quantity) AS AverageQty from dataset_project group by ReferralSource order by AverageQty DESC;

-- Among only "Delivered" orders, what is the total revenue per Product, sorted from highest to lowest?
Select Product, sum(TotalPrice) AS TotalRevenue 
from dataset_project 
where OrderStatus like "Delivered" 
group by Product 
order by TotalRevenue;
-- Which CouponCode is associated with the highest average TotalPrice, considering only orders with a coupon applied (i.e. CouponCode is not null)?
Select CouponCode, avg(TotalPrice) AS AverageTP from dataset_project 
where CouponCode is not null 
Group by CouponCode 
order by AverageTP DESC limit 1;
